//
//  Component.hpp
#pragma once

#include <bg2e/common.hpp>
#include <bg2e/math/projections.hpp>
#include <bg2e/app/KeyEvent.hpp>
#include <bg2e/json/JsonNode.hpp>

#include <string>
#include <filesystem>

#define BG2E_SCENE_COMP_CLASS_NAME(c) typeid(*c).name()

namespace bg2e {
namespace scene {

class Node;
class Scene;

class BG2E_API Component {
    friend class Node;
public:
    
    virtual ~Component() = default;
    
    inline Node * ownerNode() const { return _owner; }
    Scene * scene();

    virtual void resizeViewport(const math::Viewport&) {}
    
    /**
     * Use this function to update animation data.
     * @param delta The time elapsed since the last update call, in seconds.
     */
    virtual void animate(float) {}
    
    /**
     * Update function called every frame. Use this function to update
     * matrixes generated by the animation data.
     * @param delta The time elapsed since the last update call, in seconds.
     * 
     */
    virtual void update(float) {}
    
    /**
     * Input event: mouse move
     * @param x The x position of the mouse in window coordinates.
     * @param y The y position of the mouse in window coordinates.
     */
    virtual void mouseMove(int, int) {}

    /**
     * Input event: mouse button down
     * @param button The mouse button index.
     * @param x The x position of the mouse in window coordinates.
     * @param y The y position of the mouse in window coordinates.
     */
    virtual void mouseButtonDown(int, int, int) {}

    /**
     * Input event: mouse button up
     * @param button The mouse button index.
     * @param x The x position of the mouse in window coordinates.
     * @param y The y position of the mouse in window coordinates.
     */
    virtual void mouseButtonUp(int, int, int) {}

    /**
     * Input event: mouse wheel
     * @param deltaX The scroll delta in the x direction.
     * @param deltaY The scroll delta in the y direction.
     */
    virtual void mouseWheel(int, int) {}

    /**
     * Input event: key down
     * @param keyEvent The key event data.
     */
    virtual void keyDown(const app::KeyEvent&) {}

    /**
     * Input event: key up
     * @param keyEvent The key event data.
     */
    virtual void keyUp(const app::KeyEvent&) {}
    
    virtual std::string typeName() const = 0;
    
    virtual void deserialize(std::shared_ptr<json::JsonNode> jsonData, const std::filesystem::path& basePath);
    virtual std::shared_ptr<json::JsonNode> serialize(const std::filesystem::path& basePath);

protected:

    // Weak ptr to avoid circular references
    Node * _owner = nullptr;
    
    /**
     * Called when the component is removed from a node.
     * @param prevOwner The node from which the component was removed.
     */
    virtual void removedFromNode(Node *) {}

    /**
     * Called when the component is added to a node.
     * @param newOwner The node to which the component was added.
     */
    virtual void addedToNode(Node *) {}
};

extern BG2E_API std::string componentName(Component * comp);

#define BG2E_COMPONENT_TYPE_NAME(typeNameString) \
    static std::string staticTypeName() { return typeNameString; } \
    std::string typeName() const override { return typeNameString; }


}
}
